wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1634398829
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      - 13
      4: 3.8.8
      5: 0.12.4
      8:
      - 1
      - 3
      - 5
