wandb_version: 1

C:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1634398710
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      - 13
      - 19
      4: 3.8.8
      5: 0.12.4
      8:
      - 1
      - 3
      - 5
penalty:
  desc: null
  value: '12'
tol:
  desc: null
  value: 0.01
